#######################################################本次运行报错信息如下：#######################################################
Traceback (most recent call last):
  File "main.py", line 123, in <module>
    main()
  File "main.py", line 114, in main
    gan.train(data)
  File "/home/shenyuwang/paper_fuzzing/workspace/model/wgan/model/v1/wgan.py", line 235, in train
    lib._params.clear()
NameError: name 'lib' is not defined
Generator/Generator.InputLinear.Linear/kernel:0
Generator/Generator.InputLinear.Linear/bias:0
Generator/Generator.hidden_layer_0.Linear/kernel:0
Generator/Generator.hidden_layer_0.Linear/bias:0
Generator/Generator.hidden_layer_1.Linear/kernel:0
Generator/Generator.hidden_layer_1.Linear/bias:0
Generator/Generator.hidden_layer_2.Linear/kernel:0
Generator/Generator.hidden_layer_2.Linear/bias:0
Generator/Generator.output/kernel:0
Generator/Generator.output/bias:0
discriminator/discriminator.InputLinear.Linear/kernel:0
discriminator/discriminator.InputLinear.Linear/bias:0
discriminator/discriminator.hidden_layer_1.Linear/kernel:0
discriminator/discriminator.hidden_layer_1.Linear/bias:0
discriminator/discriminator.output/kernel:0
discriminator/discriminator.output/bias:0

#######################################################本次运行报错信息如下：#######################################################
Traceback (most recent call last):
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Generator/Generator.InputLinear.Linear/kernel
	 [[Node: Generator/Generator.InputLinear.Linear/kernel/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Generator/Generator.InputLinear.Linear/kernel)]]
	 [[Node: Round/_3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_53_Round", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 146, in <module>
    main()
  File "main.py", line 137, in main
    gan.generate_data(epoch_model_file,train_end_time)
  File "/home/shenyuwang/paper_fuzzing/workspace/model/wgan/model/v1_generate/wgan.py", line 243, in generate_data
    gen_samples = self.sess.run(self.gen_samples, feed_dict={self.z: z})
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Generator/Generator.InputLinear.Linear/kernel
	 [[Node: Generator/Generator.InputLinear.Linear/kernel/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Generator/Generator.InputLinear.Linear/kernel)]]
	 [[Node: Round/_3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_53_Round", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Generator/Generator.InputLinear.Linear/kernel/read', defined at:
  File "main.py", line 146, in <module>
    main()
  File "main.py", line 126, in main
    gan = WGAN_SEQ(sess, args, w2i, i2w,real_data_loader)
  File "/home/shenyuwang/paper_fuzzing/workspace/model/wgan/model/v1_generate/wgan.py", line 55, in __init__
    self.fake_inputs = self.generator(self.z) # [batch_size,seq_size]
  File "/home/shenyuwang/paper_fuzzing/workspace/model/wgan/model/v1_generate/wgan.py", line 121, in generator
    output = self.ReLULayer('Generator.InputLinear', self.z_dim, self.d_model, z)
  File "/home/shenyuwang/paper_fuzzing/workspace/model/wgan/model/v1_generate/wgan.py", line 106, in ReLULayer
    output = tf.layers.dense(inputs,n_out,kernel_initializer=xavier_init,name=name + '.Linear')
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/layers/core.py", line 189, in dense
    return layer.apply(inputs)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 805, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 362, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 728, in __call__
    self.build(input_shapes)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 917, in build
    trainable=True)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 276, in add_weight
    getter=vs.get_variable)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 565, in add_weight
    aggregation=aggregation)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 535, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1467, in get_variable
    aggregation=aggregation)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1217, in get_variable
    aggregation=aggregation)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 527, in get_variable
    aggregation=aggregation)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 481, in _true_getter
    aggregation=aggregation)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 903, in _get_single_variable
    aggregation=aggregation)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2443, in variable
    aggregation=aggregation)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2425, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2406, in default_variable_creator
    constraint=constraint)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 259, in __init__
    constraint=constraint)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 422, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 80, in identity
    return gen_array_ops.identity(input, name=name)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3264, in identity
    "Identity", input=input, name=name)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/shenyuwang/miniconda3/envs/env_3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value Generator/Generator.InputLinear.Linear/kernel
	 [[Node: Generator/Generator.InputLinear.Linear/kernel/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Generator/Generator.InputLinear.Linear/kernel)]]
	 [[Node: Round/_3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_53_Round", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Generator/Generator.InputLinear.Linear/kernel:0
Generator/Generator.InputLinear.Linear/bias:0
Generator/Generator.hidden_layer_0.Linear/kernel:0
Generator/Generator.hidden_layer_0.Linear/bias:0
Generator/Generator.hidden_layer_1.Linear/kernel:0
Generator/Generator.hidden_layer_1.Linear/bias:0
Generator/Generator.hidden_layer_2.Linear/kernel:0
Generator/Generator.hidden_layer_2.Linear/bias:0
Generator/Generator.output/kernel:0
Generator/Generator.output/bias:0
discriminator/discriminator.InputLinear.Linear/kernel:0
discriminator/discriminator.InputLinear.Linear/bias:0
discriminator/discriminator.hidden_layer_1.Linear/kernel:0
discriminator/discriminator.hidden_layer_1.Linear/bias:0
discriminator/discriminator.output/kernel:0
discriminator/discriminator.output/bias:0

